### ISSUE TITLE
Cannot Limit Source Path

### ISSUE THREAD

**Issue by eskemojoe007** [greglook/clj-hiera#6]
After running into #5, I wanted to run Hiera on just my backend equivalents.  Since the plugin always defaults to using the `:source-path` I had to temporarily modify this to skip my `cljs` files.  I think this could be solved in a couple of ways and I'm willing to do the pull request:

1. Don't always include `:source-path`.  If the user specifies paths, instead of merging, use the specified listing.
2. Add a `:ignore-source-path` input to remove the `:source-path` when not desired

Let me know your thoughts.

**Comment by greglook** [comment]
I like option one, but it is a change in behavior - that may not break people's workflows though, since I'd expect if you're specifying paths you probably specify everything anyway. I'd accept a PR for that change.

A second option would be a slightly more general `:ignore-files` option which accepts one or more patterns to filter files with. Then you could set `:ignore-files [#"\.cljs$"]` if you wanted to exclude all your clojurescript files.

**Comment by eskemojoe007** [comment]
I just mocked up option 1, but I found that it misses test folders, and other user specific folders you may want to include.  So I don't think its a great option.  

For reference it was as simple as updating line 169 from `source-files (find-sources (into (set (:source-paths project)) source-paths))` to `source-files (find-sources (set (or source-paths (:source-paths project))))` 

 I'll look into 2 right now.

**Comment by greglook** [comment]
In the new 2.0.0 release, the `:sources` option defaults to `#{"src"}` when used via `clj` or your project's `:source-paths` when using the Leiningen plugin. In both cases, you can provide `:sources` directly to override that to a set of paths of your choosing.
